"""
agents/vision_validator.py
===========================
Vision-overlay AI validator (Camino C4, SHADOW mode).

2026-05-20 — Builds on Camino C2 text-only validator. The key insight:
text-only C2 reads CONTEXT generated by the bot's own detectors, so
if the bot's data is wrong, Claude inherits the error (circular trust).

Vision-overlay shows Claude the raw candles WITH the bot's annotations
overlaid. Claude can independently validate:
  - Does the FVG zone the bot detected actually look like a clean FVG?
  - Is the sweep clean or a weak pivot?
  - Does the 5-min structure (MSS/BOS) appear on the chart?
  - Is the broader regime supportive (trend/range/chop)?

This breaks the "bot data feeding Claude" circular validation problem.

Inputs:
  - Text context (same as C2)
  - 1-min PNG chart (last ~90 bars) with bot annotations + proposed levels
  - 5-min PNG chart (last ~60 bars) for HTF context

Output: same JSON shape as C2 — {decision, size_multiplier, confidence, rationale}

In SHADOW mode, decision is logged to JSONL but bot continues canonical
strategy. Phase 2 active mode would gate trades based on decision.

Cost ~$0.017/call (Sonnet with 2 images), 3-6 sec latency. At ~5 unique
signals/day (after dedup), ~$0.10/day = $3/month.
"""

import base64
import json
import logging
import re
from dataclasses import dataclass, field
from datetime import datetime, timezone
from typing import Optional

try:
    import anthropic
    ANTHROPIC_AVAILABLE = True
except ImportError:
    ANTHROPIC_AVAILABLE = False

from config import ANTHROPIC_API_KEY, cfg

logger = logging.getLogger(__name__)

_VALID_DECISIONS = {"fire", "skip", "half"}
_DEFAULT_MAX_TOKENS = 800


@dataclass
class VisionValidatorDecision:
    """AI decision for a SB signal, informed by chart visuals."""

    kz: str
    decision: str
    size_multiplier: float
    confidence: float
    rationale: str
    model: str
    response_ms: int
    images_used: int = 0
    context: dict = field(default_factory=dict)
    error: Optional[str] = None

    @property
    def is_valid(self) -> bool:
        return self.error is None and self.decision in _VALID_DECISIONS

    @property
    def is_skip(self) -> bool:
        return self.decision == "skip"

    @property
    def is_half(self) -> bool:
        return self.decision == "half"

    def as_db_record(self) -> dict:
        # Note: we drop the heavy `context` field's image_b64 from the
        # DB record (too big). Context's text-only fields stay.
        ctx_lite = {k: v for k, v in self.context.items()
                    if k not in ("chart_1min_b64", "chart_5min_b64")}
        return {
            "ts": datetime.now(timezone.utc).isoformat(),
            "kz": self.kz,
            "decision": self.decision,
            "size_multiplier": float(self.size_multiplier),
            "confidence": float(self.confidence),
            "rationale": self.rationale[:500],
            "model": self.model,
            "response_ms": int(self.response_ms),
            "images_used": int(self.images_used),
            "context": ctx_lite,
            "error": self.error,
        }

    def as_telegram_message(self, shadow_mode: bool = True) -> str:
        emoji = {"fire": "[FIRE]", "half": "[HALF]", "skip": "[SKIP]"}.get(
            self.decision, "[?]"
        )
        tag = "[VISION-SHADOW] " if shadow_mode else "[VISION] "
        head = (
            f"{tag}AI Vision - KZ {self.kz.upper()}\n"
            f"{emoji} {self.decision.upper()} "
            f"(size {self.size_multiplier:.1f}x, conf {self.confidence:.2f}, "
            f"images {self.images_used})\n"
            f"Rationale: {self.rationale}"
        )
        if shadow_mode:
            head += "\n(SHADOW: bot continues canonical)"
        return head


class VisionValidatorAgent:
    """Vision-enabled validator. Sends text + chart images to Claude."""

    def __init__(
        self,
        api_key: str = ANTHROPIC_API_KEY,
        model: Optional[str] = None,
        supabase_client=None,
        telegram_bot=None,
        shadow_mode: bool = True,
        max_tokens: int = _DEFAULT_MAX_TOKENS,
    ):
        if not ANTHROPIC_AVAILABLE:
            raise ImportError("anthropic package not installed")
        if not api_key:
            raise ValueError("Anthropic API key required")

        self._model = (
            model
            or cfg("AI_MODEL_VISION_VALIDATOR", None)
            or cfg("AI_MODEL_KZ_VALIDATOR", "claude-sonnet-4-6")
        )
        self._max_tokens = max_tokens
        self._client = anthropic.Anthropic(api_key=api_key)
        self._supabase = supabase_client
        self._telegram = telegram_bot
        self._shadow_mode = shadow_mode
        logger.info(
            "VisionValidatorAgent initialized (model=%s, shadow=%s)",
            self._model, shadow_mode,
        )

    def validate_signal_with_charts(
        self,
        context: dict,
        chart_1min_b64: Optional[str],
        chart_5min_b64: Optional[str] = None,
    ) -> VisionValidatorDecision:
        """Call Claude vision API with text + images. Returns decision."""
        kz = context.get("kz", "unknown")
        # Build message content: images first, then text
        content_blocks = []
        images_used = 0
        if chart_1min_b64:
            content_blocks.append({
                "type": "image",
                "source": {
                    "type": "base64",
                    "media_type": "image/png",
                    "data": chart_1min_b64,
                },
            })
            images_used += 1
        if chart_5min_b64:
            content_blocks.append({
                "type": "image",
                "source": {
                    "type": "base64",
                    "media_type": "image/png",
                    "data": chart_5min_b64,
                },
            })
            images_used += 1
        content_blocks.append({
            "type": "text",
            "text": self._build_prompt(context, images_used),
        })

        start = datetime.now()
        try:
            message = self._client.messages.create(
                model=self._model,
                max_tokens=self._max_tokens,
                messages=[{"role": "user", "content": content_blocks}],
            )
            response_text = message.content[0].text
            elapsed_ms = int((datetime.now() - start).total_seconds() * 1000)
            decision = self._parse_response(
                response_text, context, elapsed_ms, images_used,
            )
            logger.info(
                "VisionValidator [%s] -> %s mult=%.1f conf=%.2f "
                "(images=%d, %dms)",
                kz, decision.decision, decision.size_multiplier,
                decision.confidence, images_used, elapsed_ms,
            )
            return decision
        except Exception as exc:
            elapsed_ms = int((datetime.now() - start).total_seconds() * 1000)
            logger.error("VisionValidator API call failed for %s: %s", kz, exc)
            return VisionValidatorDecision(
                kz=kz, decision="fire", size_multiplier=1.0,
                confidence=0.0, rationale=f"API error fallback: {exc}",
                model=self._model, response_ms=elapsed_ms,
                images_used=images_used, context=context, error=str(exc),
            )

    # ------------------------------------------------------------------ #
    # Prompt + parser
    # ------------------------------------------------------------------ #

    def _build_prompt(self, ctx: dict, images_used: int) -> str:
        """Build the multimodal prompt. References attached images."""
        sig = ctx.get("signal", {})
        events_str = ctx.get("high_impact_events", "none")
        prior_str = ctx.get("prior_kz_outcomes_str", "No prior KZs today")

        # Image preamble adapts to how many images were sent
        if images_used >= 2:
            image_intro = (
                "You have TWO chart images attached:\n"
                "  Image 1: 1-min chart of last ~90 min. Shows raw candles "
                "PLUS the bot's annotations: yellow ▼=swing high, "
                "blue ▲=swing low, green shaded box=bullish FVG, "
                "red shaded box=bearish FVG, level lines (PDH/PDL/PWH/PWL), "
                "and the proposed entry/stop/target as horizontal lines.\n"
                "  Image 2: 5-min HTF context chart. Shows the broader move "
                "with PDH/PDL/PWH/PWL levels highlighted."
            )
        elif images_used == 1:
            image_intro = (
                "You have ONE chart image attached: 1-min chart of last ~90 "
                "min with raw candles + bot's annotations (swings, FVGs, "
                "levels) and proposed entry/stop/target horizontal lines."
            )
        else:
            image_intro = (
                "NOTE: no chart images attached (chart generation failed). "
                "Validate based on text context only."
            )

        signal_block = ""
        if sig:
            signal_block = f"""

PROPOSED TRADE (just fired by SB):
- Direction: {sig.get('direction', '?').upper()}
- Entry: {sig.get('entry_price', 'n/a')} (FVG proximal ± 1 tick)
- Stop: {sig.get('stop_price', 'n/a')} ({sig.get('stop_pts', 'n/a')} pts risk)
- Target: {sig.get('target_price', 'n/a')} ({sig.get('target_type', 'n/a')}, {sig.get('framework_pts', 'n/a')} pts reward)
- R:R: {sig.get('actual_rr', 'n/a')}
- Contracts: {sig.get('contracts', 'n/a')}
- Confluence score: {sig.get('confluence_score', 'n/a')}/5 (SB-live; 0=structural-only, 5=A+)
- KZ: {sig.get('kill_zone', ctx.get('kz', '?'))}
"""

        return f"""You are an expert ICT validator with VISUAL access to the bot's chart. The bot has fired a Silver Bullet (SB) signal and you must vote: fire / skip / half.

{image_intro}

CRITICAL: your job is to **VALIDATE THE BOT'S CLAIMS AGAINST THE RAW CHART**. The bot's annotations are its INTERPRETATION. The candles are the truth.

What to check VISUALLY:
1. **FVG validity**: does the shaded zone look like a real 3-candle imbalance (clean displacement gap), or a noise gap from a small candle?
2. **Sweep quality**: did price actually take out a significant pivot/level, or was it a weak nick?
3. **5-min MSS/BOS validity** (if visible in chart 2): does the structural shift the bot claims actually appear on the chart, or is it a weak fluctuation?
4. **Setup location**: is the proposed entry at the FVG proximal, or has price moved away?
5. **Regime**: is this a clean trend / clean range / messy chop? (chop = high probability of failure)
6. **Counter-trend exposure**: is the trade direction vs the broader visible trend reasonable?

Respond ONLY with valid JSON, no code fences.
{signal_block}
DAY STATE:
- Trades today: {ctx.get('trades_today', 0)} (W:{ctx.get('wins_today', 0)} L:{ctx.get('losses_today', 0)})
- Daily P&L: ${float(ctx.get('daily_pnl', 0)):,.2f}
- Peak P&L: ${float(ctx.get('peak_pnl', 0)):,.2f}
- Drawdown from peak: ${float(ctx.get('drawdown_from_peak', 0)):,.2f}
- Consec losses: {ctx.get('consecutive_losses', 0)}
- Instant-adverse losses today (MFE<0.5R): {ctx.get('instant_adverse_today', 0)}
- Kill switch: {ctx.get('kill_switch_active', False)}, MLL: {ctx.get('mll_zone', 'normal')}

PRIOR KZ:
{prior_str}

HTF & MACRO:
- Daily bias: {ctx.get('daily_bias', 'n/a')}
- Weekly bias: {ctx.get('weekly_bias', 'n/a')}
- Last 5min struct events: {ctx.get('struct_last3', 'n/a')}
- Last displacement: {ctx.get('last_disp', 'n/a')}
- SWC mood: {ctx.get('swc_mood', 'n/a')} (confidence {ctx.get('swc_confidence', 'n/a')})
- News sentiment: {ctx.get('news_sentiment', 'n/a')}
- High-impact events today: {events_str}

PRICE STATE:
- Current price: {ctx.get('current_price', 'n/a')}
- Session range so far: {ctx.get('session_range_pts', 'n/a')} pts
- VPIN: {ctx.get('vpin', 'n/a')} ({ctx.get('vpin_zone', 'n/a')})

STRATEGY NOTE: SB v19a-WIDE — operates throughout full KZ (London 01:00-07:30 CT, NY AM 07:30-12:00 CT, NY PM 12:00-15:00 CT), NOT restricted to ICT canonical 1-hr sub-windows. If the signal fired, all 7 hard gates already passed (sweep + 1-min FVG + 5-min MSS/BOS + KZ + framework + stop floor + 2R target). SB does NOT require HTF bias alignment (countertrend is intentional). Confluence score is NOT a reliable gate (cross-period proven score=0 is the highest-WR bucket).

YOUR JOB: vote based on **chart validation + context**. Default to "fire" unless you see a SPECIFIC issue. Skip is for when the chart shows the bot's interpretation is wrong, the regime is hostile, or this trade is meaningfully worse than baseline SB expectancy.

RESPONSE FORMAT (strict JSON):
{{
  "decision": "fire" | "skip" | "half",
  "size_multiplier": 1.0 | 0.5 | 0.0,
  "confidence": 0.0 to 1.0,
  "rationale": "concise reason ~200-300 chars — REFERENCE specific visual observations when possible (e.g. 'FVG looks clean, sweep took out PDL, MSS confirmed' or 'FVG is noise gap, sweep barely nicked the level, chop pattern')"
}}"""

    def _parse_response(
        self,
        response_text: str,
        context: dict,
        elapsed_ms: int,
        images_used: int,
    ) -> VisionValidatorDecision:
        kz = context.get("kz", "unknown")
        clean = response_text.strip()
        # Strip code fences if Claude added them
        if clean.startswith("```"):
            m = re.match(r"^```(?:json)?\s*\n(.*?)\n```\s*$", clean, re.S)
            if m:
                clean = m.group(1).strip()
            else:
                clean = clean.split("\n", 1)[1] if "\n" in clean else clean

        try:
            data = json.loads(clean)
            decision = str(data.get("decision", "fire")).lower().strip()
            if decision not in _VALID_DECISIONS:
                logger.warning(
                    "VisionValidator: invalid decision '%s' for %s; falling back",
                    decision, kz,
                )
                decision = "fire"
            default_mult = {"fire": 1.0, "half": 0.5, "skip": 0.0}[decision]
            size_mult = float(data.get("size_multiplier", default_mult))
            confidence = float(data.get("confidence", 0.5))
            confidence = max(0.0, min(1.0, confidence))
            rationale = str(data.get("rationale", ""))[:500]

            return VisionValidatorDecision(
                kz=kz,
                decision=decision,
                size_multiplier=size_mult,
                confidence=confidence,
                rationale=rationale,
                model=self._model,
                response_ms=elapsed_ms,
                images_used=images_used,
                context=context,
            )
        except Exception as exc:
            logger.error(
                "VisionValidator parse failed for %s: %s\nResponse[:300]: %s",
                kz, exc, response_text[:300],
            )
            return VisionValidatorDecision(
                kz=kz, decision="fire", size_multiplier=1.0,
                confidence=0.0, rationale=f"Parse error: {exc}",
                model=self._model, response_ms=elapsed_ms,
                images_used=images_used, context=context, error=str(exc),
            )


def validate_signal_with_charts(
    context: dict,
    chart_1min_b64: Optional[str],
    chart_5min_b64: Optional[str] = None,
    api_key: str = ANTHROPIC_API_KEY,
    model: Optional[str] = None,
    shadow_mode: bool = True,
) -> VisionValidatorDecision:
    """Module-level convenience function."""
    agent = VisionValidatorAgent(
        api_key=api_key, model=model, shadow_mode=shadow_mode,
    )
    return agent.validate_signal_with_charts(
        context, chart_1min_b64, chart_5min_b64
    )
