"""
agents/vision_validator.py
===========================
Vision-overlay AI validator (Camino C4, SHADOW mode).

2026-05-20 — Builds on Camino C2 text-only validator. The key insight:
text-only C2 reads CONTEXT generated by the bot's own detectors, so
if the bot's data is wrong, Claude inherits the error (circular trust).

Vision-overlay shows Claude the raw candles WITH the bot's annotations
overlaid. Claude can independently validate:
  - Does the FVG zone the bot detected actually look like a clean FVG?
  - Is the sweep clean or a weak pivot?
  - Does the 5-min structure (MSS/BOS) appear on the chart?
  - Is the broader regime supportive (trend/range/chop)?

This breaks the "bot data feeding Claude" circular validation problem.

Inputs:
  - Text context (same as C2)
  - 1-min PNG chart (last ~90 bars) with bot annotations + proposed levels
  - 5-min PNG chart (last ~60 bars) for HTF context

Output: same JSON shape as C2 — {decision, size_multiplier, confidence, rationale}

In SHADOW mode, decision is logged to JSONL but bot continues canonical
strategy. Phase 2 active mode would gate trades based on decision.

Cost ~$0.017/call (Sonnet with 2 images), 3-6 sec latency. At ~5 unique
signals/day (after dedup), ~$0.10/day = $3/month.
"""

import base64
import json
import logging
import re
from dataclasses import dataclass, field
from datetime import datetime, timezone
from typing import Optional

try:
    import anthropic
    ANTHROPIC_AVAILABLE = True
except ImportError:
    ANTHROPIC_AVAILABLE = False

from config import ANTHROPIC_API_KEY, cfg

logger = logging.getLogger(__name__)

_VALID_DECISIONS = {"fire", "skip", "half"}
_DEFAULT_MAX_TOKENS = 800


@dataclass
class VisionValidatorDecision:
    """AI decision for a SB signal, informed by chart visuals."""

    kz: str
    decision: str
    size_multiplier: float
    confidence: float
    rationale: str
    model: str
    response_ms: int
    images_used: int = 0
    context: dict = field(default_factory=dict)
    # 2026-05-21 — separate assessment of whether the BOT is reading the
    # chart correctly. Independent of the trade decision. Lets us
    # accumulate data on which detector calls Claude considers accurate
    # vs questionable vs wrong — critical for identifying systematic
    # detector errors (the original motivation for vision overlay).
    bot_assessment: dict = field(default_factory=dict)
    error: Optional[str] = None

    @property
    def is_valid(self) -> bool:
        return self.error is None and self.decision in _VALID_DECISIONS

    @property
    def is_skip(self) -> bool:
        return self.decision == "skip"

    @property
    def is_half(self) -> bool:
        return self.decision == "half"

    def as_db_record(self) -> dict:
        # Note: we drop the heavy `context` field's image_b64 from the
        # DB record (too big). Context's text-only fields stay.
        ctx_lite = {k: v for k, v in self.context.items()
                    if k not in ("chart_1min_b64", "chart_5min_b64")}
        return {
            "ts": datetime.now(timezone.utc).isoformat(),
            "kz": self.kz,
            "decision": self.decision,
            "size_multiplier": float(self.size_multiplier),
            "confidence": float(self.confidence),
            "rationale": self.rationale[:500],
            "model": self.model,
            "response_ms": int(self.response_ms),
            "images_used": int(self.images_used),
            "context": ctx_lite,
            "bot_assessment": self.bot_assessment,
            "error": self.error,
        }

    def as_telegram_message(self, shadow_mode: bool = True) -> str:
        emoji = {"fire": "[FIRE]", "half": "[HALF]", "skip": "[SKIP]"}.get(
            self.decision, "[?]"
        )
        tag = "[VISION-SHADOW] " if shadow_mode else "[VISION] "
        msg = (
            f"{tag}AI Vision - KZ {self.kz.upper()}\n"
            f"{emoji} {self.decision.upper()} "
            f"(size {self.size_multiplier:.1f}x, conf {self.confidence:.2f}, "
            f"images {self.images_used})\n"
            f"Rationale: {self.rationale}"
        )
        # Bot assessment summary if available
        if self.bot_assessment:
            ba = self.bot_assessment
            overall = ba.get("overall", "")
            fvg_a = ba.get("fvg_assessment", "")
            sweep_a = ba.get("sweep_assessment", "")
            mss_a = ba.get("mss_assessment", "")
            if any([overall, fvg_a, sweep_a, mss_a]):
                msg += f"\n\nBot accuracy: FVG={fvg_a} | sweep={sweep_a} | MSS={mss_a}"
                if overall:
                    msg += f"\n  {overall}"
        if shadow_mode:
            msg += "\n(SHADOW: bot continues canonical)"
        return msg


class VisionValidatorAgent:
    """Vision-enabled validator. Sends text + chart images to Claude."""

    def __init__(
        self,
        api_key: str = ANTHROPIC_API_KEY,
        model: Optional[str] = None,
        supabase_client=None,
        telegram_bot=None,
        shadow_mode: bool = True,
        max_tokens: int = _DEFAULT_MAX_TOKENS,
    ):
        if not ANTHROPIC_AVAILABLE:
            raise ImportError("anthropic package not installed")
        if not api_key:
            raise ValueError("Anthropic API key required")

        self._model = (
            model
            or cfg("AI_MODEL_VISION_VALIDATOR", None)
            or cfg("AI_MODEL_KZ_VALIDATOR", "claude-sonnet-4-6")
        )
        self._max_tokens = max_tokens
        self._client = anthropic.Anthropic(api_key=api_key)
        self._supabase = supabase_client
        self._telegram = telegram_bot
        self._shadow_mode = shadow_mode
        logger.info(
            "VisionValidatorAgent initialized (model=%s, shadow=%s)",
            self._model, shadow_mode,
        )

    def validate_signal_with_charts(
        self,
        context: dict,
        chart_1min_b64: Optional[str],
        chart_5min_b64: Optional[str] = None,
    ) -> VisionValidatorDecision:
        """Call Claude vision API with text + images. Returns decision."""
        kz = context.get("kz", "unknown")
        # Build message content: images first, then text
        content_blocks = []
        images_used = 0
        if chart_1min_b64:
            content_blocks.append({
                "type": "image",
                "source": {
                    "type": "base64",
                    "media_type": "image/png",
                    "data": chart_1min_b64,
                },
            })
            images_used += 1
        if chart_5min_b64:
            content_blocks.append({
                "type": "image",
                "source": {
                    "type": "base64",
                    "media_type": "image/png",
                    "data": chart_5min_b64,
                },
            })
            images_used += 1
        content_blocks.append({
            "type": "text",
            "text": self._build_prompt(context, images_used),
        })

        start = datetime.now()
        try:
            message = self._client.messages.create(
                model=self._model,
                max_tokens=self._max_tokens,
                messages=[{"role": "user", "content": content_blocks}],
            )
            response_text = message.content[0].text
            elapsed_ms = int((datetime.now() - start).total_seconds() * 1000)
            decision = self._parse_response(
                response_text, context, elapsed_ms, images_used,
            )
            logger.info(
                "VisionValidator [%s] -> %s mult=%.1f conf=%.2f "
                "(images=%d, %dms)",
                kz, decision.decision, decision.size_multiplier,
                decision.confidence, images_used, elapsed_ms,
            )
            return decision
        except Exception as exc:
            elapsed_ms = int((datetime.now() - start).total_seconds() * 1000)
            logger.error("VisionValidator API call failed for %s: %s", kz, exc)
            return VisionValidatorDecision(
                kz=kz, decision="fire", size_multiplier=1.0,
                confidence=0.0, rationale=f"API error fallback: {exc}",
                model=self._model, response_ms=elapsed_ms,
                images_used=images_used, context=context, error=str(exc),
            )

    # ------------------------------------------------------------------ #
    # Prompt + parser
    # ------------------------------------------------------------------ #

    def _build_prompt(self, ctx: dict, images_used: int) -> str:
        """Build the multimodal prompt. References attached images."""
        sig = ctx.get("signal", {})
        events_str = ctx.get("high_impact_events", "none")
        prior_str = ctx.get("prior_kz_outcomes_str", "No prior KZs today")

        # Image preamble adapts to how many images were sent
        if images_used >= 2:
            image_intro = (
                "You have TWO chart images attached:\n"
                "  Image 1: 1-min chart of last ~90 min. Shows raw candles "
                "PLUS the bot's annotations: yellow ▼=swing high, "
                "blue ▲=swing low, green shaded box=bullish FVG, "
                "red shaded box=bearish FVG, level lines (PDH/PDL/PWH/PWL), "
                "and the proposed entry/stop/target as horizontal lines.\n"
                "  Image 2: 5-min HTF context chart. Shows the broader move "
                "with PDH/PDL/PWH/PWL levels highlighted."
            )
        elif images_used == 1:
            image_intro = (
                "You have ONE chart image attached: 1-min chart of last ~90 "
                "min with raw candles + bot's annotations (swings, FVGs, "
                "levels) and proposed entry/stop/target horizontal lines."
            )
        else:
            image_intro = (
                "NOTE: no chart images attached (chart generation failed). "
                "Validate based on text context only."
            )

        signal_block = ""
        if sig:
            signal_block = f"""

PROPOSED TRADE (just fired by SB):
- Direction: {sig.get('direction', '?').upper()}
- Entry: {sig.get('entry_price', 'n/a')} (FVG proximal ± 1 tick)
- Stop: {sig.get('stop_price', 'n/a')} ({sig.get('stop_pts', 'n/a')} pts risk)
- Target: {sig.get('target_price', 'n/a')} ({sig.get('target_type', 'n/a')}, {sig.get('framework_pts', 'n/a')} pts reward)
- R:R: {sig.get('actual_rr', 'n/a')}
- Contracts: {sig.get('contracts', 'n/a')}
- Confluence score: {sig.get('confluence_score', 'n/a')}/5 (SB-live; 0=structural-only, 5=A+)
- KZ: {sig.get('kill_zone', ctx.get('kz', '?'))}
"""

        return f"""You are an ICT (Inner Circle Trader) trade validator with VISUAL access to a Silver Bullet (SB) chart. The bot has fired a setup and you must do TWO jobs:

  JOB 1: Vote on the trade — fire / skip / half
  JOB 2: Assess whether the bot is reading the chart CORRECTLY (independent of the trade vote)

{image_intro}

═══════════════════════════════════════════════════════════════════
ICT CANONICAL RULES (from ICT 2024 Mentorship — these are the LAW)
═══════════════════════════════════════════════════════════════════

A) SILVER BULLET ENTRY MODEL
   - **FVG-only** entry (NEVER OB-based). First FVG in the SB window is the trigger.
   - **NO bias alignment required.** SB can go LONG or SHORT regardless of D1/W1 bias.
   - Driver is "draw on liquidity" — where price hunts stops next, NOT what bias says.
   - **COUNTER-TREND IS INTENTIONAL** — do NOT vote skip just because trade direction
     disagrees with HTF. ICT quote: "no es necesariamente el bias, predominantemente solo
     tienes que considerar dónde está el próximo nivel de atracción de liquidez."
   - Setup must form INSIDE the kill zone; trade can extend beyond to reach target.

B) FVG VALIDITY (canonical)
   - Must BREAK a balanced price range — not just consolidation noise.
   - Must be tethered to sweep + displacement (post-MSS shift).
   - Must sit BELOW 50% of dealing range (for buys), ABOVE 50% (for sells).
   - **NO minimum size rule** — even "real small tiny" FVGs are valid per ICT.
   - **NOT invalidated** at 50-75% retracement; only invalid when BODY closes through distal.
   - Entry: candle 3 proximal edge ± 1 tick. No rejection wait.

C) SWEEP + MSS REQUIREMENTS
   - Sweep of previous highs/lows MUST happen BEFORE the FVG (not after).
   - MSS = market structure shift with displacement (2-3× normal candle body).
   - Sweep + MSS + FVG = all three boxes checked = valid setup.

D) TARGET = LIQUIDITY POOL (never fixed RR)
   - Targets are PDH/PDL/PWH/PWL/equal highs-lows/old swings/imbalance gaps.
   - MNQ minimum framework: 10 pts / 40 ticks to next pool.

E) JUDAS SWING WARNING (post-open trap)
   - First FVG in first 30 min after NY equity open (08:30 CT / 09:30 ET) often becomes
     IFVG 90% of time. Algorithm INTENTIONALLY crosses to create liquidity.
   - Implication: be cautious of fresh FVGs in 08:30-09:00 CT window.

F) BE WARNING — "Don't move stop to BE too quickly. Let the move develop."

═══════════════════════════════════════════════════════════════════
VISUAL PATTERN REFERENCE — how to recognize each pattern (explained
slowly, as if teaching a 3-year-old). The bot annotates the chart;
your job is to verify those annotations are correct.
═══════════════════════════════════════════════════════════════════

YOU ARE LOOKING AT A CANDLESTICK CHART. Each candle has:
  • A BODY (rectangle) — GREEN if close > open (bullish), RED if close < open (bearish)
  • WICKS (thin lines extending up/down) — show intra-bar high and low
  • X-axis = time (left = older, right = newer/now)
  • Y-axis = price (higher up = higher price)

The bot has DRAWN annotations on top of the candles:
  • Yellow ▼ marker = bot's claimed SWING HIGH pivot
  • Blue ▲ marker = bot's claimed SWING LOW pivot
  • Green semi-transparent rectangle = bot's claimed BULLISH FVG zone
  • Red semi-transparent rectangle = bot's claimed BEARISH FVG zone
  • Purple/yellow dashed horizontal lines = ACTIVE liquidity levels
    (labeled e.g. "PDH 29420", "PDL 28814", "PWH 29784", "NAH 29395", "NAL 28663")
  • Dotted gray horizontal lines with "(SWEPT)" tag = levels ALREADY taken out
  • Solid yellow horizontal line + "ENTRY" label = proposed trade entry price
  • Dashed red horizontal line + "STOP" label = proposed stop
  • Dashed green horizontal line + "TARGET" label = proposed target

────────────────────────────────────────────────────────────────────
📊 FAIR VALUE GAP (FVG) — how to tell REAL from FAKE
────────────────────────────────────────────────────────────────────

A FVG is a 3-candle pattern with a GAP (empty vertical space) between candle 1
and candle 3. Middle candle (candle 2) does the "displacement" — moves fast.

BULLISH FVG (the bot draws a GREEN rectangle here):
  - Look at 3 consecutive candles on the chart.
  - Candle 1 (oldest of the three) has some HIGH (top of its upper wick).
  - Candle 2 (middle) is supposed to be a LARGE green candle pushing UP hard.
    Its body should be visibly BIGGER than candles before/after.
  - Candle 3 (newest) has some LOW (bottom of its lower wick).
  - The FVG is the VERTICAL EMPTY SPACE between candle 1's HIGH and candle 3's LOW.

  Mental picture (ASCII):

      candle 1       candle 2         candle 3
      ___                              ___
     |   |       ┃━━━━━━━━━━━━┃       |   |
     | █ |       ┃    BIG     ┃       | █ |
     |___|       ┃    GREEN   ┃       |___|
                 ┃    BODY    ┃
                 ┃            ┃     ← candle 3 LOW
                 ┃            ┃
                 ┃            ┃     ← FVG empty space (the gap)
                 ┃            ┃
                 ┃            ┃     ← candle 1 HIGH
                 ┗━━━━━━━━━━━━┛

  ✅ REAL bullish FVG looks like:
     - The middle candle is CLEARLY larger than candles before AND after
     - There is a VISIBLE empty vertical space between c1 and c3
     - The gap is shaded GREEN by the bot
     - Comes AFTER a sweep of lows

  ❌ FAKE bullish FVG looks like:
     - All 3 candles are roughly the same size (no displacement on c2)
     - No clear empty space — candles overlap each other
     - The "gap" is tiny and inside choppy candles
     - No prior sweep — just appeared in the middle of a range

BEARISH FVG is the MIRROR (bot draws RED rectangle):
  - Candle 2 should be a BIG RED candle pushing DOWN
  - Gap is between candle 1's LOW and candle 3's HIGH
  - Comes after a sweep of highs

────────────────────────────────────────────────────────────────────
🎯 LIQUIDITY SWEEP — how to tell REAL from FAKE
────────────────────────────────────────────────────────────────────

A sweep happens when price PIERCES a horizontal level (a swing high/low,
or labeled level like PDH/PDL) with a wick, and then REJECTS BACK.

The dashed horizontal lines on the chart ARE these levels. Look for one
of them being pierced by a candle wick.

REAL bullish sweep (sweep of lows, before a long entry):
                                                ▼
                              _________        | C |  ← rejection candle:
                             |    C    |       |   |    long wick BELOW level,
                             |    1    |       |___|    body CLOSES above
       ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─|     ← dashed line (a low level)
                             |         |        |
                             |_________|        |       ← long wick PIERCES below
                                  |             |
                                  ↓             ↓
                                wick extends below the level
                                then candle closes back above

  ✅ REAL: wick CLEARLY pierces below the dashed line. Body closes ABOVE the level.
     The candle "looks like a tail" with the body up and a long wick below.
  ❌ FAKE: wick barely touches the line (no clear pierce). OR the candle body
     closes BELOW the level (that's a break, not a sweep). OR no clear level
     was even pierced — wick just dips into open space.

BEARISH sweep (sweep of highs) is the mirror: long UPPER wick above a high level,
body closes BELOW.

────────────────────────────────────────────────────────────────────
📈 MSS / BOS / CHoCH — structural shifts
────────────────────────────────────────────────────────────────────

The chart has yellow ▼ (swing highs) and blue ▲ (swing lows). These are
your reference pivots for structure.

BOS BULLISH (Break of Structure, continuation up):
  - Price was making LOWER HIGHS or in a RANGE.
  - A candle CLOSES (body, not just wick) ABOVE the last yellow ▼.
  - Visually: you see the candle body fully above the previous swing high marker.

BOS BEARISH (continuation down):
  - Mirror: candle body closes BELOW the last blue ▲ (recent swing low).

CHoCH (Change of Character):
  - The FIRST opposite-direction break of structure after a trend.
  - Example: price was making higher highs/lows (uptrend). Then a candle body
    closes BELOW the last blue ▲. That's CHoCH bearish — first sign of reversal.

MSS (Market Structure Shift):
  - A CHoCH or BOS that happens WITH a large displacement candle.
  - More reliable than a weak structure break.

  ✅ REAL MSS/BOS: break candle has a LARGE body, clearly closes through the level.
  ❌ FAKE: just a wick crosses (no body close). Or the break candle is tiny/weak.

────────────────────────────────────────────────────────────────────
💥 DISPLACEMENT — the "kick" that makes things valid
────────────────────────────────────────────────────────────────────

Displacement = a candle whose BODY is MUCH LARGER than the surrounding candles.

  Normal candles (no displacement):
     [ ] [ ] [ ] [ ] [ ]    ← all roughly the same size

  WITH displacement:
     [ ] [ ] ╔══════════╗ [ ] [ ]
            ║   BIG    ║          ← clearly stands out, 2-3× normal size
            ║   BODY   ║
            ╚══════════╝

  - REAL FVG requires displacement on candle 2.
  - REAL MSS requires displacement on the break candle.
  - Without displacement = no institutional momentum = setup is weak.

────────────────────────────────────────────────────────────────────
🎚️ DEALING RANGE — Premium vs Discount
────────────────────────────────────────────────────────────────────

Mentally divide the VISIBLE chart range into 2 halves:

  ─────────────────  ← Highest point on chart
       │
       │  PREMIUM (upper 50%) — shorts preferred here
       │
  ─────┼─────────── ← equilibrium midline (50%)
       │
       │  DISCOUNT (lower 50%) — longs preferred here
       │
  ─────────────────  ← Lowest point on chart

  ✅ LONG entry should be in DISCOUNT (lower half) — buying low.
  ✅ SHORT entry should be in PREMIUM (upper half) — selling high.
  ⚠️ LONG entry that's in PREMIUM (top of range) is suspicious — chasing the move.
  ⚠️ SHORT entry that's in DISCOUNT (bottom of range) is suspicious — fading the lows.

────────────────────────────────────────────────────────────────────
⏰ JUDAS SWING — the 8:30 CT trap (NY AM only)
────────────────────────────────────────────────────────────────────

After NY equity open at 8:30 CT (9:30 ET), the FIRST FVG that forms in the
first 30 minutes is OFTEN a TRAP. ICT says 90% of the time, this initial FVG
gets INVERTED (becomes an IFVG = polarity flip from FVG to its opposite).

  Mechanism: the algorithm creates the FVG INTENTIONALLY to trap traders
  into the wrong direction, then reverses to grab the liquidity those traders
  just placed.

  Visual sign: a clean-looking FVG that forms within ~30 min of 8:30 CT,
  often after a fake breakout move. Looks "too obvious."

  ⚠️ If this is NY AM and the proposed trade is based on a fresh post-open
  FVG (signal time within ~30 min of 08:30 CT), bias toward SKIP or HALF.

────────────────────────────────────────────────────────────────────
🌊 REGIME — Trend vs Range vs Chop
────────────────────────────────────────────────────────────────────

Look at the OVERALL shape of the 5-min chart (image 2):

  TREND (clean directional):
    - Candles consistently making higher highs + higher lows (bull)
    - OR lower highs + lower lows (bear)
    - Clear staircase pattern
    - SB winners common in trends (continuation after sweep)

  RANGE (clean horizontal):
    - Candles oscillating between two clear horizontal levels
    - Sweeps at the edges of the range (both highs and lows)
    - SB winners VERY common (this is the IDEAL SB regime — mean reversion plays)

  CHOP (messy, no structure):
    - Candles overlapping, no clear direction
    - No clean horizontal levels — random spikes both ways
    - Multiple structure events (BOS/CHoCH) flipping back and forth rapidly
    - Like trying to read tea leaves
    - SB struggles HARD in chop

  ✅ Trend or Range → OK to fire
  ❌ Pure chop → lean toward SKIP

═══════════════════════════════════════════════════════════════════
WHAT JUSTIFIES SKIP (be SPECIFIC — cite visual observations)
═══════════════════════════════════════════════════════════════════
  ✓ FVG zone shaded by bot is NOT a real imbalance (no displacement c2,
    no visible empty space, just chop candles)
  ✓ NO visible sweep precedes the FVG (no candle wick clearly pierces a level)
  ✓ Target line has no real liquidity pool visible nearby (no labeled level
    or swing pivot within target distance)
  ✓ Pure chop regime visible on 5-min (overlapping candles, no structure)
  ✓ Judas swing situation (NY AM, fresh FVG <30min after 08:30 CT)
  ✓ MSS that bot claims is NOT visible on the chart, or contradicted by
    subsequent candles
  ✓ FVG zone is in PREMIUM half for a LONG trade (or DISCOUNT for SHORT) —
    counter-positional

═══════════════════════════════════════════════════════════════════
WHAT DOES NOT JUSTIFY SKIP (do NOT vote skip for these)
═══════════════════════════════════════════════════════════════════
  ✗ "Counter-trend vs daily/weekly bias" — SB doesn't require HTF align
  ✗ "Confluence score is low (0 or 1)" — score=0 is the highest-WR bucket
    in 3-yr cross-period validation
  ✗ "Stop tight" or "Stop wide" — SB uses structural stops, not R-multiples
  ✗ "Outside canonical 1-hr ICT window" — bot uses v19a-WIDE
  ✗ "Day already negative" or "consec losses" — that's risk mgmt, not setup
    quality

═══════════════════════════════════════════════════════════════════
WHAT JUSTIFIES HALF (mild concerns, not full skip)
═══════════════════════════════════════════════════════════════════
  ⚠️ FVG quality marginal (small displacement on c2 but visible)
  ⚠️ Sweep marginal but present (small pierce, weak rejection)
  ⚠️ Mid-regime ambiguity (turning from trend to range, etc.)
  ⚠️ Day already in significant drawdown but setup is structurally OK

{signal_block}
DAY STATE:
- Trades today: {ctx.get('trades_today', 0)} (W:{ctx.get('wins_today', 0)} L:{ctx.get('losses_today', 0)})
- Daily P&L: ${float(ctx.get('daily_pnl', 0)):,.2f}
- Peak P&L: ${float(ctx.get('peak_pnl', 0)):,.2f}
- Drawdown from peak: ${float(ctx.get('drawdown_from_peak', 0)):,.2f}
- Consec losses: {ctx.get('consecutive_losses', 0)}
- Instant-adverse losses today (MFE<0.5R): {ctx.get('instant_adverse_today', 0)}
- Kill switch: {ctx.get('kill_switch_active', False)}, MLL: {ctx.get('mll_zone', 'normal')}

PRIOR KZ TODAY:
{prior_str}

HTF & MACRO:
- Daily bias (informational only — SB doesn't require align): {ctx.get('daily_bias', 'n/a')}
- Weekly bias (informational only): {ctx.get('weekly_bias', 'n/a')}
- Last 5min struct events: {ctx.get('struct_last3', 'n/a')}
- Last displacement: {ctx.get('last_disp', 'n/a')}
- SWC mood: {ctx.get('swc_mood', 'n/a')} (confidence {ctx.get('swc_confidence', 'n/a')})
- News sentiment: {ctx.get('news_sentiment', 'n/a')}
- High-impact events today: {events_str}

PRICE STATE:
- Current price: {ctx.get('current_price', 'n/a')}
- Session range so far: {ctx.get('session_range_pts', 'n/a')} pts
- VPIN: {ctx.get('vpin', 'n/a')} ({ctx.get('vpin_zone', 'n/a')})

═══════════════════════════════════════════════════════════════════
YOUR OUTPUT
═══════════════════════════════════════════════════════════════════

DEFAULT TO "fire" unless you see a SPECIFIC ICT-canonical issue from the
"WHAT JUSTIFIES SKIP" list above. SB has positive cross-period expectancy.

Respond ONLY with valid JSON, no code fences:

{{
  "decision": "fire" | "skip" | "half",
  "size_multiplier": 1.0 | 0.5 | 0.0,
  "confidence": 0.0 to 1.0,
  "rationale": "concise reason ~200-300 chars — CITE specific visual observations from the chart (e.g. 'FVG c1-c3 gap clean with big c2 green displacement, sweep of PDL visible at 28814, target PWH 29784 in clear sight, range regime') AND ICT canonical rule when applicable",
  "bot_assessment": {{
    "fvg_assessment": "accurate" | "questionable" | "wrong" | "missing",
    "sweep_assessment": "accurate" | "questionable" | "wrong" | "missing",
    "mss_assessment": "accurate" | "questionable" | "wrong" | "missing",
    "overall": "short sentence on whether the bot's interpretation of the chart matches what you see (e.g. 'Bot annotations match the chart well — FVG is real, sweep is clean' or 'Bot called an FVG but I see no displacement on c2, looks like noise')"
  }}
}}

NOTES on bot_assessment:
- "accurate" = bot's annotation matches what you see visually
- "questionable" = there's something there but quality is marginal
- "wrong" = bot's claim is NOT supported by the visible candles
- "missing" = annotation not visible / not applicable / chart unclear

bot_assessment is INDEPENDENT of the trade decision. You can vote FIRE even
if bot_assessment flags issues (the trade may still work for other reasons).
You can vote SKIP even if bot_assessment is accurate (other factors dominant).
The two outputs are tracked separately for counterfactual analysis."""

    def _parse_response(
        self,
        response_text: str,
        context: dict,
        elapsed_ms: int,
        images_used: int,
    ) -> VisionValidatorDecision:
        kz = context.get("kz", "unknown")
        clean = response_text.strip()
        # Strip code fences if Claude added them
        if clean.startswith("```"):
            m = re.match(r"^```(?:json)?\s*\n(.*?)\n```\s*$", clean, re.S)
            if m:
                clean = m.group(1).strip()
            else:
                clean = clean.split("\n", 1)[1] if "\n" in clean else clean

        try:
            data = json.loads(clean)
            decision = str(data.get("decision", "fire")).lower().strip()
            if decision not in _VALID_DECISIONS:
                logger.warning(
                    "VisionValidator: invalid decision '%s' for %s; falling back",
                    decision, kz,
                )
                decision = "fire"
            default_mult = {"fire": 1.0, "half": 0.5, "skip": 0.0}[decision]
            size_mult = float(data.get("size_multiplier", default_mult))
            confidence = float(data.get("confidence", 0.5))
            confidence = max(0.0, min(1.0, confidence))
            rationale = str(data.get("rationale", ""))[:500]

            # 2026-05-21 — bot_assessment: independent evaluation of whether
            # the bot is reading the chart correctly. Always parse defensively;
            # use empty dict if missing or malformed.
            bot_assessment = {}
            ba_raw = data.get("bot_assessment", {})
            if isinstance(ba_raw, dict):
                valid_assessments = {"accurate", "questionable", "wrong", "missing"}
                for k in ("fvg_assessment", "sweep_assessment", "mss_assessment"):
                    v = str(ba_raw.get(k, "")).lower().strip()
                    if v in valid_assessments:
                        bot_assessment[k] = v
                    elif v:
                        # Unknown value — log but don't crash
                        logger.debug(
                            "bot_assessment %s invalid value: %s", k, v,
                        )
                        bot_assessment[k] = v[:30]  # store truncated for analysis
                overall = ba_raw.get("overall")
                if overall:
                    bot_assessment["overall"] = str(overall)[:300]

            return VisionValidatorDecision(
                kz=kz,
                decision=decision,
                size_multiplier=size_mult,
                confidence=confidence,
                rationale=rationale,
                model=self._model,
                response_ms=elapsed_ms,
                images_used=images_used,
                context=context,
                bot_assessment=bot_assessment,
            )
        except Exception as exc:
            logger.error(
                "VisionValidator parse failed for %s: %s\nResponse[:300]: %s",
                kz, exc, response_text[:300],
            )
            return VisionValidatorDecision(
                kz=kz, decision="fire", size_multiplier=1.0,
                confidence=0.0, rationale=f"Parse error: {exc}",
                model=self._model, response_ms=elapsed_ms,
                images_used=images_used, context=context, error=str(exc),
            )


def validate_signal_with_charts(
    context: dict,
    chart_1min_b64: Optional[str],
    chart_5min_b64: Optional[str] = None,
    api_key: str = ANTHROPIC_API_KEY,
    model: Optional[str] = None,
    shadow_mode: bool = True,
) -> VisionValidatorDecision:
    """Module-level convenience function."""
    agent = VisionValidatorAgent(
        api_key=api_key, model=model, shadow_mode=shadow_mode,
    )
    return agent.validate_signal_with_charts(
        context, chart_1min_b64, chart_5min_b64
    )
