"""
strategy_lab/types.py
======================
Shared dataclasses used by every Strategy Lab module.

These are intentionally lightweight: the Lab doesn't know about
specific strategies or the backtester's internals. It speaks in
metrics (Sharpe, win rate, drawdown) and passes a ``runner`` callable
that produces those metrics from a slice of data.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Callable, Optional, Protocol

import pandas as pd


# ─── Metrics contract — what every backtest returns ─────────────────────

@dataclass
class BacktestMetrics:
    """
    Canonical metrics shape the Lab understands.

    Adapters wrap the real backtester output into this shape so the Lab
    stays decoupled from backtester implementation details.
    """
    sharpe: float = 0.0
    win_rate: float = 0.0        # 0.0–1.0
    max_drawdown: float = 0.0    # 0.0–1.0 (fraction of equity)
    total_pnl: float = 0.0
    total_trades: int = 0
    profit_factor: float = 0.0
    start_date: Optional[pd.Timestamp] = None
    end_date: Optional[pd.Timestamp] = None


# ─── Runner protocol — what the Lab calls to evaluate a hypothesis ──────

class BacktestRunner(Protocol):
    """
    Strategy-agnostic callable interface used by every Lab component.

    Any function matching this signature can be plugged into the Lab:
      def runner(data, use_hypothesis, hypothesis_config) -> BacktestMetrics
    """
    def __call__(
        self,
        data: pd.DataFrame,
        *,
        use_hypothesis: bool,
        hypothesis_config: Optional[dict] = None,
    ) -> BacktestMetrics: ...


# ─── Hypothesis definition ──────────────────────────────────────────────

@dataclass
class Hypothesis:
    """
    An ICT-grounded trading hypothesis.

    Generated by HypothesisGenerator (Claude API) and consumed by
    lab_engine.run_pipeline(). Each hypothesis MUST have a fundamental
    ICT reason — arbitrary parameter combinations are rejected.
    """
    id: str                         # e.g. "H-001"
    name: str                       # Short descriptive name
    ict_reasoning: str              # Why this should work (2-3 sentences)
    condition: str                  # Exact boolean condition (pseudocode)
    parameters_added: int           # 0, 1, or 2 (Occam's razor gate)
    expected_impact: str            # What metric should improve
    risk: str                       # Honest failure mode
    config: dict = field(default_factory=dict)  # optional runtime params

    def to_dict(self) -> dict:
        return {
            "id": self.id,
            "name": self.name,
            "ict_reasoning": self.ict_reasoning,
            "condition": self.condition,
            "parameters_added": self.parameters_added,
            "expected_impact": self.expected_impact,
            "risk": self.risk,
            "config": self.config,
        }

    @classmethod
    def from_dict(cls, d: dict) -> "Hypothesis":
        return cls(
            id=d["id"],
            name=d["name"],
            ict_reasoning=d.get("ict_reasoning", ""),
            condition=d.get("condition", ""),
            parameters_added=int(d.get("parameters_added", 0)),
            expected_impact=d.get("expected_impact", ""),
            risk=d.get("risk", ""),
            config=d.get("config", {}),
        )


# ─── Gate outcome (shared by anti_overfit_gates + candidate_manager) ────

@dataclass
class GateResult:
    """Outcome of a single anti-overfit gate."""
    gate_name: str
    passed: bool
    metric: float
    threshold: float
    reason: str

    def to_dict(self) -> dict:
        return {
            "gate_name": self.gate_name,
            "passed": self.passed,
            "metric": self.metric,
            "threshold": self.threshold,
            "reason": self.reason,
        }


# ─── Lab pipeline outcome ───────────────────────────────────────────────

@dataclass
class PipelineResult:
    """Complete outcome of running one hypothesis through all 9 gates."""
    hypothesis: Hypothesis
    gates: list[GateResult] = field(default_factory=list)
    baseline_metrics: Optional[BacktestMetrics] = None
    hypothesis_metrics: Optional[BacktestMetrics] = None

    # Aggregate signals from each stage
    walk_forward_positive_pct: float = 0.0
    instruments_passing: int = 0
    noise_resilience: float = 1.0
    inversion_loses: bool = False
    validation_improvement: float = 0.0

    status: str = "pending"  # pending | running | passed | failed | approved | rejected
    failure_stage: Optional[str] = None
    score: int = 0            # 0–100 composite

    @property
    def all_gates_passed(self) -> bool:
        return len(self.gates) > 0 and all(g.passed for g in self.gates)

    @property
    def gates_passed_count(self) -> int:
        return sum(1 for g in self.gates if g.passed)
