"""
backtest/backtester.py
=======================
Historical strategy simulation engine.

Walks candle-by-candle through 1-min OHLCV data. At each bar:

  1. Check for open-position exit (stop / target / hard-close).
  2. If no position, advance HTF bar indices (entry TF + context TF) and
     trigger the strategy only when a new entry-TF bar has *fully closed*.
  3. On signal: open a simulated position (limit fill at signal.entry_price).
  4. Record every trade and every signal; aggregate daily P&L.

The strategy interface required
-------------------------------
Strategies must expose:
  - ENTRY_TF          : class attr — '1min' | '5min' | '15min' | ...
  - CONTEXT_TF        : class attr — same choices
  - evaluate(df_entry, df_context) -> Signal | None
  - reset_daily()     : called at every new calendar-date boundary

Performance notes
-----------------
- Hot loop reads numpy arrays for high/low/close; no per-candle dataclass
  allocation.
- HTF frames are aggregated once at run start via TimeframeManager (cache
  cleared first to avoid stale caches from prior runs).
- Detector updates receive a bounded trailing slice (DETECTOR_LOOKBACK_*)
  to keep per-bar work O(lookback) instead of O(total bars).
- Detector updates and `strategy.evaluate` only run when a new entry-TF
  bar has closed — never on every 1-min tick.

Conservatism
------------
- If stop AND target appear inside the same 1-min bar, STOP wins (worst case).
- Entry fills immediately at signal.entry_price on the signal bar; exit
  checks begin the next 1-min bar (no same-bar round-trip).
- Hard close (3:00 PM CT) flattens at that bar's close price.
- Session reset uses calendar date in US/Central.
"""

import logging
from dataclasses import dataclass, field
from typing import Optional
import datetime

import pandas as pd

import sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

import config

logger = logging.getLogger(__name__)

# Bounded trailing windows for per-bar detector updates.
# Keep these >= the longest lookback any ICT pattern needs on that TF.
DETECTOR_LOOKBACK_ENTRY = 150
DETECTOR_LOOKBACK_CONTEXT = 150

# MNQ dollar value per point — single source of truth is config.MNQ_POINT_VALUE
from config import MNQ_POINT_VALUE  # noqa: E402  (re-exported for test imports)


@dataclass
class Trade:
    """A completed (closed) trade in the backtest."""

    strategy: str
    symbol: str
    direction: str              # 'long' | 'short'
    entry_time: pd.Timestamp
    exit_time: pd.Timestamp
    entry_price: float
    stop_price: float
    target_price: float
    exit_price: float
    contracts: int
    pnl: float                  # dollars
    reason: str                 # 'target' | 'stop' | 'hard_close'
    confluence_score: int
    duration_bars: int          # number of 1-min bars held
    kill_zone: str = ""         # which KZ produced this trade

    def __repr__(self) -> str:
        return (
            f"Trade({self.strategy} {self.direction} "
            f"{self.entry_price:.2f}->{self.exit_price:.2f} x{self.contracts} "
            f"pnl=${self.pnl:+.2f} [{self.reason}])"
        )


@dataclass
class SignalLog:
    """Every signal generated by the strategy (all were taken by construction)."""

    timestamp: pd.Timestamp
    strategy: str
    direction: str
    entry_price: float
    stop_price: float
    target_price: float
    contracts: int
    confluence_score: int
    kill_zone: str = ""


@dataclass
class BacktestResult:
    """Aggregate result returned by Backtester.run()."""

    strategy: str
    trades: list                   # list[Trade]
    signals: list                  # list[SignalLog]
    daily_pnl: dict                # datetime.date -> float
    total_pnl: float
    total_trades: int
    wins: int
    losses: int
    win_rate: float
    total_signals: int
    start_date: Optional[pd.Timestamp] = None
    end_date: Optional[pd.Timestamp] = None

    def __repr__(self) -> str:
        return (
            f"BacktestResult(strategy={self.strategy} "
            f"trades={self.total_trades} wins={self.wins}/{self.losses} "
            f"win_rate={self.win_rate:.1%} pnl=${self.total_pnl:+.2f})"
        )


VALID_TRADE_MGMT = ("fixed", "partials_be", "trailing")


class Backtester:
    """
    Candle-by-candle strategy simulator.

    Parameters
    ----------
    strategy        : strategy instance with ENTRY_TF, CONTEXT_TF, evaluate(), reset_daily()
    detectors       : dict — standard detector bag shared with the strategy;
                      may contain 'swing_entry', 'swing_context', 'structure',
                      'fvg', 'ob', 'displacement', 'liquidity', 'confluence',
                      'tracked_levels'. Missing keys are skipped silently.
    risk_manager    : RiskManager instance
    tf_manager      : TimeframeManager instance (its cache is cleared at run start)
    session_manager : SessionManager instance (used by strategy, not backtester)
    trade_management: "fixed" (default) | "partials_be" | "trailing"
                      fixed      — standard 1:RR exit at stop/target
                      partials_be — at 1R close 50 %, move stop to BE; remainder runs to target
                      trailing   — no fixed target; stop trails last 5min swing low/high
    """

    def __init__(
        self,
        strategy,
        detectors: dict,
        risk_manager,
        tf_manager,
        session_manager,
        trade_management: Optional[str] = None,
    ):
        # Default to config.TRADE_MANAGEMENT so backtest and live share the
        # same exit regime out of the box. Prior default "fixed" silently
        # diverged from live (which reads config directly) — meta-audit
        # 2026-04-17 flagged every backtest this week ran fixed exits
        # while live ran trailing. Explicit arg still wins.
        if trade_management is None:
            trade_management = getattr(config, "TRADE_MANAGEMENT", "fixed")
        if trade_management not in VALID_TRADE_MGMT:
            raise ValueError(
                f"trade_management must be one of {VALID_TRADE_MGMT}, got {trade_management!r}"
            )
        self.strategy = strategy
        self.detectors = detectors
        self.risk = risk_manager
        self.tf = tf_manager
        self.session = session_manager
        self.trade_management = trade_management

        self.trades: list = []
        self.signals: list = []

    # ------------------------------------------------------------------ #
    # Public API                                                           #
    # ------------------------------------------------------------------ #

    def run(
        self,
        df_1min: pd.DataFrame,
        start_date: Optional[str] = None,
        end_date: Optional[str] = None,
    ) -> BacktestResult:
        """
        Execute the backtest.

        Parameters
        ----------
        df_1min    : pd.DataFrame — 1-min OHLCV with tz-aware DatetimeIndex (CT)
        start_date : str, optional — 'YYYY-MM-DD' inclusive
        end_date   : str, optional — 'YYYY-MM-DD' inclusive

        Returns
        -------
        BacktestResult
        """
        # Reset accumulators (safe to call run() multiple times on one instance)
        self.trades = []
        self.signals = []

        df = self._filter_dates(df_1min, start_date, end_date)
        if df.empty:
            return self._empty_result()

        entry_tf = getattr(self.strategy, "ENTRY_TF", "5min")
        context_tf = getattr(self.strategy, "CONTEXT_TF", "15min")

        # Clear stale cache before aggregating
        if hasattr(self.tf, "clear_cache"):
            self.tf.clear_cache()

        df_entry = df if entry_tf == "1min" else self.tf.aggregate(df, entry_tf)
        df_context = self.tf.aggregate(df, context_tf)

        # Optional HTF frames (D/W). Tolerate failures on tiny data ranges.
        try:
            df_daily = self.tf.aggregate(df, "D")
        except Exception:  # pragma: no cover
            df_daily = pd.DataFrame()
        try:
            df_weekly = self.tf.aggregate(df, "W")
        except Exception:  # pragma: no cover
            df_weekly = pd.DataFrame()

        # Hot-loop arrays
        ts_index = df.index
        high_arr = df["high"].values
        low_arr = df["low"].values
        close_arr = df["close"].values

        entry_index = df_entry.index
        context_index = df_context.index
        entry_delta = self._tf_delta(entry_tf)
        context_delta = self._tf_delta(context_tf)

        # State
        open_position: Optional[dict] = None
        pending_entry: Optional[dict] = None   # unfilled limit order
        last_entry_idx: int = -1
        current_session_date: Optional[datetime.date] = None
        daily_pnl: dict = {}
        _limit_ttl = getattr(config, "LIMIT_ORDER_TTL_BARS", 10)

        n = len(df)
        for i in range(n):
            current_ts = ts_index[i]
            bar_high = float(high_arr[i])
            bar_low = float(low_arr[i])
            bar_close = float(close_arr[i])
            current_date = current_ts.date()

            # ── Session reset at every new calendar date (CT) ─────────
            if current_session_date != current_date:
                self.risk.reset_daily()
                if hasattr(self.strategy, "reset_daily"):
                    self.strategy.reset_daily()
                current_session_date = current_date
                daily_pnl[current_date] = 0.0
                # Advance last_entry_idx marker so we still evaluate today's first bar
                # (no-op — intentionally keep it; a new day may or may not advance the idx)

            # ── 0. Pending limit entry: check fill or TTL ────────────
            if pending_entry is not None and open_position is None:
                lp = pending_entry["limit_price"]
                if pending_entry["direction"] == "long" and bar_low <= lp:
                    open_position = dict(pending_entry)
                    open_position["entry_price"] = lp
                    open_position["entry_bar_idx"] = i
                    open_position.pop("limit_price", None)
                    open_position.pop("bars_waiting", None)
                    pending_entry = None
                elif pending_entry["direction"] == "short" and bar_high >= lp:
                    open_position = dict(pending_entry)
                    open_position["entry_price"] = lp
                    open_position["entry_bar_idx"] = i
                    open_position.pop("limit_price", None)
                    open_position.pop("bars_waiting", None)
                    pending_entry = None
                else:
                    pending_entry["bars_waiting"] = pending_entry.get("bars_waiting", 0) + 1
                    if pending_entry["bars_waiting"] >= _limit_ttl:
                        logger.debug(
                            "LIMIT TTL: %s %s limit @ %.2f expired after %d bars",
                            pending_entry["strategy"], pending_entry["direction"],
                            pending_entry["limit_price"], _limit_ttl,
                        )
                        pending_entry = None

            # ── 1. Check open-position exit first ─────────────────────
            if open_position is not None:
                # Don't allow same-bar round-trip: skip exit check on entry bar
                if i == open_position["entry_bar_idx"]:
                    pass
                else:
                    if self.trade_management == "partials_be":
                        closed_trades = self._process_partials_be(
                            open_position, bar_high, bar_low, bar_close, current_ts, i,
                        )
                    elif self.trade_management == "trailing":
                        self._update_trailing_stop(open_position)
                        closed_trades = self._process_fixed(
                            open_position, bar_high, bar_low, bar_close, current_ts, i,
                        )
                    else:
                        closed_trades = self._process_fixed(
                            open_position, bar_high, bar_low, bar_close, current_ts, i,
                        )

                    for trade in closed_trades:
                        self.trades.append(trade)
                        self.risk.record_trade(trade.pnl)
                        if hasattr(self.risk, 'record_trading_day'):
                            self.risk.record_trading_day(current_date)
                        daily_pnl[current_date] = (
                            daily_pnl.get(current_date, 0.0) + trade.pnl
                        )

                    if open_position.get("closed"):
                        open_position = None

            if open_position is not None:
                continue

            # ── 2. Advance HTF indices (bars fully closed only) ────────
            new_entry_idx = self._latest_closed_idx(
                entry_index, current_ts, entry_delta,
            )
            if new_entry_idx < 0 or new_entry_idx == last_entry_idx:
                continue
            last_entry_idx = new_entry_idx

            new_context_idx = self._latest_closed_idx(
                context_index, current_ts, context_delta,
            )
            if new_context_idx < 0:
                continue

            # ── 3. Bounded trailing slices ─────────────────────────────
            e_start = max(0, new_entry_idx + 1 - DETECTOR_LOOKBACK_ENTRY)
            c_start = max(0, new_context_idx + 1 - DETECTOR_LOOKBACK_CONTEXT)
            df_entry_slice = df_entry.iloc[e_start: new_entry_idx + 1]
            df_context_slice = df_context.iloc[c_start: new_context_idx + 1]

            # ── 4. Update detectors (idempotent; skips seen timestamps) ─
            self._update_detectors(
                df_entry_slice, df_context_slice, entry_tf, context_tf,
            )

            # ── 5. Sweep check on current 1-min bar ────────────────────
            self._update_sweeps(bar_high, bar_low, bar_close)

            # ── 6. Strategy evaluation — skip if a limit order is waiting
            if pending_entry is not None:
                continue

            signal = self.strategy.evaluate(df_entry_slice, df_context_slice)
            if signal is None:
                continue

            # ── 6b. Cruise mode overrides ─────────────────────────────
            sig_contracts = int(signal.contracts)
            sig_stop = float(signal.stop_price)
            sig_target = float(signal.target_price)

            if getattr(self.risk, 'cruise_mode', False):
                # Force 1 contract
                sig_contracts = self.risk.cruise_max_contracts
                # Check max risk ($100) — reject if stop too wide
                stop_pts = abs(float(signal.entry_price) - sig_stop)
                trade_risk = stop_pts * sig_contracts * MNQ_POINT_VALUE
                if trade_risk > self.risk.cruise_max_risk:
                    logger.debug(
                        "Cruise: reject trade risk=$%.0f > $%.0f",
                        trade_risk, self.risk.cruise_max_risk,
                    )
                    continue
                # Tighten target to 1:1 RR in cruise (preserve capital)
                if signal.direction == "long":
                    sig_target = float(signal.entry_price) + stop_pts
                else:
                    sig_target = float(signal.entry_price) - stop_pts

            # ── 7. Log signal & queue as pending limit entry ───────────
            self.signals.append(SignalLog(
                timestamp=signal.timestamp,
                strategy=signal.strategy,
                direction=signal.direction,
                entry_price=float(signal.entry_price),
                stop_price=sig_stop,
                target_price=sig_target,
                contracts=sig_contracts,
                confluence_score=int(signal.confluence_score),
                kill_zone=signal.kill_zone,
            ))

            pending_entry = {
                "strategy": signal.strategy,
                "symbol": signal.symbol,
                "direction": signal.direction,
                "kill_zone": signal.kill_zone,
                "entry_time": current_ts,
                "limit_price": float(signal.entry_price),
                "stop_price": sig_stop,
                "target_price": sig_target,
                "contracts": sig_contracts,
                "confluence_score": int(signal.confluence_score),
                "bars_waiting": 0,
            }

            # Advance per-zone + daily trade counters at order placement
            # (not fill) to prevent double-signals during the wait window.
            if hasattr(self.strategy, "notify_trade_executed"):
                self.strategy.notify_trade_executed(signal)

        return self._build_result(daily_pnl, df.index[0], df.index[-1])

    # ------------------------------------------------------------------ #
    # Exit / P&L                                                            #
    # ------------------------------------------------------------------ #

    def _calc_pnl(self, direction: str, entry: float, exit_px: float, contracts: int) -> float:
        if direction == "long":
            return (exit_px - entry) * contracts * MNQ_POINT_VALUE
        return (entry - exit_px) * contracts * MNQ_POINT_VALUE

    def _check_raw_exit(
        self,
        pos: dict,
        bar_high: float,
        bar_low: float,
        bar_close: float,
        current_ts: pd.Timestamp,
    ) -> Optional[dict]:
        """Return {'exit_price', 'reason'} or None. Stop wins over target."""
        if self.risk.check_hard_close(current_ts):
            return {"exit_price": bar_close, "reason": "hard_close"}
        direction = pos["direction"]
        stop = pos["stop_price"]
        target = pos.get("target_price")
        if direction == "long":
            if bar_low <= stop:
                return {"exit_price": stop, "reason": "stop"}
            if target is not None and bar_high >= target:
                return {"exit_price": target, "reason": "target"}
        else:
            if bar_high >= stop:
                return {"exit_price": stop, "reason": "stop"}
            if target is not None and bar_low <= target:
                return {"exit_price": target, "reason": "target"}
        return None

    def _make_trade(self, pos: dict, exit_px: float, reason: str,
                    current_ts: pd.Timestamp, current_bar_idx: int,
                    contracts: Optional[int] = None) -> Trade:
        contracts = contracts if contracts is not None else pos["contracts"]
        pnl = self._calc_pnl(pos["direction"], pos["entry_price"], exit_px, contracts)
        return Trade(
            strategy=pos["strategy"],
            symbol=pos["symbol"],
            direction=pos["direction"],
            entry_time=pos["entry_time"],
            exit_time=current_ts,
            entry_price=pos["entry_price"],
            stop_price=pos["stop_price"],
            target_price=pos.get("target_price", pos["entry_price"]),
            exit_price=exit_px,
            contracts=contracts,
            pnl=pnl,
            reason=reason,
            confluence_score=pos["confluence_score"],
            duration_bars=current_bar_idx - pos["entry_bar_idx"],
            kill_zone=pos.get("kill_zone", ""),
        )

    def _process_fixed(
        self,
        pos: dict,
        bar_high: float,
        bar_low: float,
        bar_close: float,
        current_ts: pd.Timestamp,
        current_bar_idx: int,
    ) -> list:
        """Standard fixed stop/target. Returns list[Trade] (0 or 1)."""
        exit_info = self._check_raw_exit(pos, bar_high, bar_low, bar_close, current_ts)
        if exit_info is None:
            return []
        trade = self._make_trade(pos, exit_info["exit_price"], exit_info["reason"],
                                 current_ts, current_bar_idx)
        pos["closed"] = True
        return [trade]

    def _process_partials_be(
        self,
        pos: dict,
        bar_high: float,
        bar_low: float,
        bar_close: float,
        current_ts: pd.Timestamp,
        current_bar_idx: int,
    ) -> list:
        """
        Partials + break-even management:
          1. At 1R (entry + stop_distance): close floor(contracts/2), move stop → entry (BE)
          2. Remaining half runs to original target.
          3. If BE hit after partial: remaining closes at entry → $0 on remainder.
        Returns list[Trade] with 0, 1, or 2 trades.
        """
        trades_out: list = []
        direction = pos["direction"]
        entry = pos["entry_price"]
        stop = pos["stop_price"]
        stop_dist = abs(entry - stop)

        # ── Phase A: partial not yet taken ─────────────────────────────
        if not pos.get("partial_done"):
            # 1R level
            if direction == "long":
                one_r = entry + stop_dist
                partial_hit = bar_high >= one_r
            else:
                one_r = entry - stop_dist
                partial_hit = bar_low <= one_r

            # Check stop before partial (stop always wins)
            if self.risk.check_hard_close(current_ts):
                trade = self._make_trade(pos, bar_close, "hard_close", current_ts, current_bar_idx)
                pos["closed"] = True
                return [trade]

            if direction == "long" and bar_low <= stop:
                trade = self._make_trade(pos, stop, "stop", current_ts, current_bar_idx)
                pos["closed"] = True
                return [trade]
            if direction == "short" and bar_high >= stop:
                trade = self._make_trade(pos, stop, "stop", current_ts, current_bar_idx)
                pos["closed"] = True
                return [trade]

            if partial_hit:
                # Close 50% contracts (floor division)
                total = pos["contracts"]
                partial_contracts = total // 2
                remaining = total - partial_contracts
                partial_pnl_px = one_r

                partial_trade = self._make_trade(
                    pos, partial_pnl_px, "partial",
                    current_ts, current_bar_idx, contracts=partial_contracts,
                )
                trades_out.append(partial_trade)

                # Update position: move stop to entry (BE), reduce contracts
                pos["stop_price"] = entry
                pos["contracts"] = remaining
                pos["partial_done"] = True
                pos["partial_contracts_closed"] = partial_contracts

                # Same bar: check if full target also hit (spike through both 1R and target)
                target = pos.get("target_price")
                if target is not None:
                    if direction == "long" and bar_high >= target:
                        rem_trade = self._make_trade(
                            pos, target, "target", current_ts, current_bar_idx,
                            contracts=remaining,
                        )
                        trades_out.append(rem_trade)
                        pos["closed"] = True
                    elif direction == "short" and bar_low <= target:
                        rem_trade = self._make_trade(
                            pos, target, "target", current_ts, current_bar_idx,
                            contracts=remaining,
                        )
                        trades_out.append(rem_trade)
                        pos["closed"] = True
                return trades_out

            return []  # nothing triggered this bar

        # ── Phase B: partial already taken, BE stop + target ───────────
        exit_info = self._check_raw_exit(pos, bar_high, bar_low, bar_close, current_ts)
        if exit_info is None:
            return []
        trade = self._make_trade(pos, exit_info["exit_price"], exit_info["reason"],
                                 current_ts, current_bar_idx)
        pos["closed"] = True
        return [trade]

    def _update_trailing_stop(self, pos: dict) -> None:
        """
        Advance the trailing stop to the most recent swing low (long) or
        swing high (short) detected by swing_entry, if it improves the stop.
        Only tightens — never widens.
        """
        swing = self.detectors.get("swing_entry")
        if swing is None:
            return
        direction = pos["direction"]
        current_stop = pos["stop_price"]
        if direction == "long":
            sp = swing.get_latest_swing_low()
            if sp is not None and sp.price > current_stop:
                pos["stop_price"] = sp.price
        else:
            sp = swing.get_latest_swing_high()
            if sp is not None and sp.price < current_stop:
                pos["stop_price"] = sp.price

    # ------------------------------------------------------------------ #
    # Detectors / sweeps                                                    #
    # ------------------------------------------------------------------ #

    def _update_detectors(
        self,
        df_entry: pd.DataFrame,
        df_context: pd.DataFrame,
        entry_tf: str,
        context_tf: str,
    ) -> None:
        """
        Run each available detector's incremental update.

        All detectors are optional — missing keys are skipped. Detectors
        are designed to skip timestamps they've already processed, so
        repeated calls with growing trailing windows are safe.
        """
        d = self.detectors

        swing_entry = d.get("swing_entry")
        if swing_entry is not None and not df_entry.empty:
            swing_entry.detect(df_entry, entry_tf)

        swing_context = d.get("swing_context")
        if swing_context is not None and not df_context.empty:
            swing_context.detect(df_context, context_tf)

        structure = d.get("structure")
        if structure is not None and swing_context is not None and not df_context.empty:
            new_struct_events = structure.update(df_context, swing_context, context_tf)
            ob = d.get("ob")
            if ob is not None:
                for _ev in new_struct_events:
                    if _ev.type in ("BOS", "CHoCH", "MSS"):
                        ob.invalidate_by_structure(_ev.direction)

        fvg = d.get("fvg")
        if fvg is not None and not df_entry.empty:
            fvg.detect(df_entry, entry_tf)
            # Age active FVGs against the latest close. Without this call
            # FVGs are never marked mitigated AND IFVGs are never born —
            # the backtest used to see a strictly monotonic FVG pool while
            # live saw a realistic pool that turns over. Meta-audit
            # 2026-04-17 flagged this as the largest backtest/live
            # asymmetry. candle_body + atr_14 are computed on the entry
            # TF (mirrors main.py:855-870). When the window is too small
            # for a 14-period ATR, pass None — fvg.update_mitigation
            # degrades to "no IFVG conversion" and just ages FVGs.
            last_bar = df_entry.iloc[-1]
            close_price = float(last_bar["close"])
            body_px = abs(float(last_bar["close"]) - float(last_bar["open"]))
            atr_14: Optional[float] = None
            if len(df_entry) >= 15:
                import numpy as _np
                highs = df_entry["high"].values[-14:]
                lows = df_entry["low"].values[-14:]
                prev_closes = df_entry["close"].values[-15:-1]
                tr = _np.maximum(
                    highs - lows,
                    _np.maximum(
                        _np.abs(highs - prev_closes),
                        _np.abs(lows - prev_closes),
                    ),
                )
                atr_14 = float(tr.mean())
            fvg.update_mitigation(
                close_price, candle_body=body_px, atr_14=atr_14,
            )

        ob = d.get("ob")
        if ob is not None and not df_entry.empty:
            ob.detect(df_entry, entry_tf, swing_entry, fvg)
            ob.expire_old(df_entry.index[-1])

        displacement = d.get("displacement")
        if displacement is not None and not df_entry.empty:
            displacement.detect(df_entry, entry_tf)

    def _update_sweeps(
        self,
        bar_high: float,
        bar_low: float,
        bar_close: float,
    ) -> None:
        """
        Mark tracked liquidity levels as swept if the current 1-min bar
        pierced them with a close back on the original side.

        Uses raw floats (no pd.Series) to stay hot-loop-cheap.
        """
        levels = self.detectors.get("tracked_levels")
        if not levels:
            return

        _bsl = {"BSL", "PDH", "PWH", "equal_highs"}
        _ssl = {"SSL", "PDL", "PWL", "equal_lows"}

        for level in levels:
            if level.swept:
                continue
            if level.type in _bsl:
                if bar_high > level.price and bar_close < level.price:
                    level.swept = True
            elif level.type in _ssl:
                if bar_low < level.price and bar_close > level.price:
                    level.swept = True

    # ------------------------------------------------------------------ #
    # Helpers                                                              #
    # ------------------------------------------------------------------ #

    @staticmethod
    def _tf_delta(tf: str) -> pd.Timedelta:
        """Bar duration for a timeframe label."""
        mapping = {
            "1min": pd.Timedelta(minutes=1),
            "5min": pd.Timedelta(minutes=5),
            "15min": pd.Timedelta(minutes=15),
            "1H": pd.Timedelta(hours=1),
            "4H": pd.Timedelta(hours=4),
            "D": pd.Timedelta(hours=23),
            "W": pd.Timedelta(days=5),
        }
        return mapping.get(tf, pd.Timedelta(minutes=1))

    @staticmethod
    def _latest_closed_idx(
        ts_index: pd.DatetimeIndex,
        current_ts: pd.Timestamp,
        delta: pd.Timedelta,
    ) -> int:
        """
        Index of the most recent bar whose close-time <= current_ts.

        A bar labeled T with duration delta closes at T + delta. Return the
        largest idx where ts_index[idx] <= current_ts - delta.  Returns -1
        if no bar has closed yet.
        """
        cutoff = current_ts - delta
        idx = int(ts_index.searchsorted(cutoff, side="right")) - 1
        return idx

    @staticmethod
    def _filter_dates(
        df: pd.DataFrame,
        start_date: Optional[str],
        end_date: Optional[str],
    ) -> pd.DataFrame:
        """Date-range filter. Inputs are 'YYYY-MM-DD' strings in US/Central."""
        if df.empty:
            return df
        tz = df.index.tz
        if start_date:
            df = df[df.index >= pd.Timestamp(start_date, tz=tz)]
        if end_date:
            end_ts = pd.Timestamp(end_date, tz=tz) + pd.Timedelta(days=1)
            df = df[df.index < end_ts]
        return df

    # ------------------------------------------------------------------ #
    # Result builders                                                      #
    # ------------------------------------------------------------------ #

    def _build_result(
        self,
        daily_pnl: dict,
        start: pd.Timestamp,
        end: pd.Timestamp,
    ) -> BacktestResult:
        total_pnl = sum(t.pnl for t in self.trades)
        wins = sum(1 for t in self.trades if t.pnl > 0)
        losses = sum(1 for t in self.trades if t.pnl <= 0)
        total = len(self.trades)
        win_rate = (wins / total) if total > 0 else 0.0

        return BacktestResult(
            strategy=type(self.strategy).__name__,
            trades=list(self.trades),
            signals=list(self.signals),
            daily_pnl=dict(daily_pnl),
            total_pnl=total_pnl,
            total_trades=total,
            wins=wins,
            losses=losses,
            win_rate=win_rate,
            total_signals=len(self.signals),
            start_date=start,
            end_date=end,
        )

    def _empty_result(self) -> BacktestResult:
        return BacktestResult(
            strategy=type(self.strategy).__name__,
            trades=[],
            signals=[],
            daily_pnl={},
            total_pnl=0.0,
            total_trades=0,
            wins=0,
            losses=0,
            win_rate=0.0,
            total_signals=0,
        )
